version: "3.4"

services:
  app:
    build: ./build/app
    ports: 
      - 8080:80
    depends_on:
      - db
    volumes:
      - ./storage:/srv/www/storage
  db:
    build: ./build/db
    volumes:
      - ./mongodb/data/db:/data/db