port: 3000
# api
jwt: jsonwebtokensecret
storage: ../storage/
database: mongodb://127.0.0.1:27017/rugodb
models:
  files: 
    __type: filesystem
admin:
  email: admin@example.com
  apiKey: defaultapikey
  password: defaultpassword
# view
viewDir: ../storage/files/views